{"uuid": "85ba87d3-2e6a-4ea0-b2b0-f50566249095", "children": ["088e6b2c-20b5-4106-b140-d76cf629639c", "04f3d6d3-bc3a-4ce1-b17b-3f2a5bd7fee1", "8367e93f-278e-4a9f-affd-c76eabe6ce13", "c3598ca8-4228-4a72-9dc3-be9221ef780e", "36743ef5-1f56-424e-b7d6-690bf42decb1"], "befores": [{"name": "InitElectronDriver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities\n  (Driver info: chromedriver=2.36 (7ea271f92018b1eeb8e70ec6de8c29f9758a0c05),platform=Windows NT 10.0.19044 x86_64)\n\n", "trace": "  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\AtidAutomation\\FullStackFinalProject\\TestCases\\conftest.py\", line 185, in InitElectronDriver\n    globals()[\"driver\"] = GetElectronDriver()\n  File \"D:\\AtidAutomation\\FullStackFinalProject\\TestCases\\conftest.py\", line 200, in GetElectronDriver\n    driver = selenium.webdriver.Chrome(options=options, executable_path=GetData(\"ElectronDriver\"))\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 272, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 364, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1666691135854, "stop": 1666691143011}], "start": 1666691135854, "stop": 1666691143528}